import type { SectionMeta } from "./types";

/**
 * Pure, serializable metadata for every section in the library — the single
 * source of truth for `docs/sections/CATALOG.md`. Carries NO React references
 * so it can be imported by a plain Node script (`scripts/gen-section-catalog.mjs`).
 * `registry.ts` pairs each entry (by `id`) with its live component + sample props.
 *
 * `category` = audience/origin · `useCase` = the job the section does.
 */
const REF = "../design-references";

export const SECTION_META = [
  // ── Home ────────────────────────────────────────────────────────────────
  {
    id: "home-hero",
    displayName: "Home — Hero",
    useCase: "hero",
    category: "home",
    description: "Full-bleed hero: centered oversized brand title + two intro paragraphs over a photo.",
    propsSummary: [
      { name: "bgImage", type: "string", required: true },
      { name: "title", type: "string", required: true },
      { name: "intro", type: "string", required: true },
      { name: "body", type: "string", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec1-hero.png`,
  },
  {
    id: "home-discover",
    displayName: "Home — Discover",
    useCase: "discover",
    category: "home",
    description: "Eyebrow + heading, kitchen photo with interactive hotspots, team photo + intro, and a 4-blurb row.",
    propsSummary: [
      { name: "eyebrow", type: "string", required: true },
      { name: "heading", type: "string", required: true },
      { name: "kitchenImage", type: "string", required: true },
      { name: "hotspots", type: "Hotspot[]", required: true },
      { name: "teamImage", type: "string", required: true },
      { name: "teamHeading", type: "string", required: true },
      { name: "teamBody", type: "string", required: true },
      { name: "blurbs", type: "Blurb[]", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec2-discover.png`,
  },
  {
    id: "home-quality",
    displayName: "Home — Quality",
    useCase: "quality",
    category: "home",
    description: "Large multi-line headline + two paragraphs, followed by a 3-image gallery.",
    propsSummary: [
      { name: "headingLines", type: "string[]", required: true },
      { name: "paragraphs", type: "string[]", required: true },
      { name: "images", type: "string[]", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec3-quality.png`,
  },
  {
    id: "home-parallax",
    displayName: "Home — Parallax Quote",
    useCase: "parallax-quote",
    category: "home",
    description: "Fixed-attachment background with radial gradient; centered heading, body and italic quote.",
    propsSummary: [
      { name: "bgImage", type: "string", required: true },
      { name: "heading", type: "string", required: true },
      { name: "body", type: "string", required: true },
      { name: "quote", type: "string", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec4-parallax.png`,
  },
  {
    id: "home-handwerk",
    displayName: "Home — Handwerk Tabs",
    useCase: "handwerk-tabs",
    category: "home",
    description: "Heading + animated counters, a tab bar, and a tabbed image + 3-card panel.",
    propsSummary: [
      { name: "eyebrow", type: "string", required: true },
      { name: "headingLines", type: "string[]", required: true },
      { name: "stats", type: "CounterStat[]", required: true },
      { name: "tabs", type: "TabPanel[]", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec5-handwerk-tabs.png`,
    isClient: true,
  },
  {
    id: "home-planner",
    displayName: "Home — Planner Embed",
    useCase: "planner-embed",
    category: "home",
    description: "Eyebrow + heading wrapping an embedded iframe of the external Möbelplaner, plus an open-in-tab CTA.",
    propsSummary: [
      { name: "eyebrow", type: "string", required: true },
      { name: "heading", type: "string", required: true },
      { name: "plannerUrl", type: "string", required: true },
      { name: "ctaLabel", type: "string", required: true },
      { name: "ctaHref", type: "string", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec6-moebelplaner.png`,
  },
  {
    id: "home-raeume",
    displayName: "Home — Räume Showcase",
    useCase: "rooms-showcase",
    category: "home",
    description: "Centered intro + 3-column project showcase with the oversized 'Fast' wordmark and a ratings badge.",
    propsSummary: [
      { name: "heading / subheading / body", type: "string", required: true },
      { name: "story/kitchen/bath images + captions", type: "string", required: true },
      { name: "badge", type: "string", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec7-raeume.png`,
  },
  {
    id: "home-testimonials",
    displayName: "Home — Testimonials + Logos",
    useCase: "testimonials",
    category: "home",
    description: "Oversized heading, a single featured testimonial card, and an infinite partner-logo marquee.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "testimonial", type: "Testimonial", required: true },
      { name: "logos", type: "PartnerLogo[]", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec8-testimonials.png`,
  },
  {
    id: "home-faq",
    displayName: "Home — FAQ",
    useCase: "faq",
    category: "home",
    description: "Single-column accordion (plus/minus, yellow active border) with an eyebrow, heading and CTA.",
    propsSummary: [
      { name: "eyebrow", type: "string", required: true },
      { name: "heading", type: "string", required: true },
      { name: "items", type: "FaqItem[]", required: true },
      { name: "ctaLabel / ctaHref", type: "string", required: true },
    ],
    usedOn: ["/"],
    screenshot: `${REF}/sec9-faq.png`,
    isClient: true,
  },

  // ── Privat (möbel-nach-mass template) ─────────────────────────────────────
  {
    id: "privat-hero",
    displayName: "Privat — Hero",
    useCase: "hero",
    category: "privat",
    description: "Service hero with split layout: left H1 + breadcrumb, right intro paragraph, over a photo (Urbanist).",
    propsSummary: [
      { name: "bgImage / imageAlt", type: "string", required: true },
      { name: "title", type: "string", required: true },
      { name: "intro", type: "string", required: true },
      { name: "breadcrumb", type: "BreadcrumbItem[]", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/01-hero.jpg`,
  },
  {
    id: "privat-intro-stats",
    displayName: "Privat — Intro + Stats",
    useCase: "intro-stats",
    category: "privat",
    description: "Three-column intro (since/heading/asterisk-paragraph), a full-width image band, and a 3-column block with a scroll-triggered count-up.",
    propsSummary: [
      { name: "heading / intro* / col1–3 copy", type: "string", required: true },
      { name: "counterTarget / counterDuration", type: "number", required: true },
      { name: "links (col1/col3)", type: "string", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/02a-intro-stats.jpg`,
    isClient: true,
  },
  {
    id: "privat-process",
    displayName: "Privat — Process",
    useCase: "process",
    category: "privat",
    description: "Two-column: heading + paragraph (with trailing bold) + decorative dots on the left, image on the right.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "paragraph / paragraphStrong", type: "string", required: true },
      { name: "image / imageAlt", type: "string", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/03-process.jpg`,
  },
  {
    id: "privat-weitere-leistungen",
    displayName: "Privat — Weitere Leistungen (Services Grid)",
    useCase: "services-grid",
    category: "shared",
    description: "Eyebrow + heading and a 6-cell grid of dark service cards plus a white ampersand card. Defaults to the canonical Fast services; also used by the gewerbe page.",
    propsSummary: [
      { name: "eyebrow / heading", type: "string", required: false },
      { name: "cards", type: "ServiceCard[]", required: false },
      { name: "ampersandText / moreLabel", type: "string", required: false },
    ],
    usedOn: ["/moebel-nach-mass", "/gewerbe"],
    screenshot: `${REF}/moebel-nach-mass/04-weitere-leistungen.jpg`,
  },
  {
    id: "privat-typische",
    displayName: "Privat — Categories (Typische)",
    useCase: "categories-list",
    category: "privat",
    description: "Heading + two alternating image/list rows of titled category items.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "image1/2 + alt", type: "string", required: true },
      { name: "row1 / row2", type: "CategoryItem[]", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/05-typische.jpg`,
  },
  {
    id: "privat-warum",
    displayName: "Privat — Warum (Masonry + Text)",
    useCase: "gallery-masonry",
    category: "privat",
    description: "CSS-columns masonry collage on the left, heading + paragraph + decorative dots on the right.",
    propsSummary: [
      { name: "heading / paragraph", type: "string", required: true },
      { name: "images", type: "WarumImage[]", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/06-warum.jpg`,
  },
  {
    id: "privat-geschichte",
    displayName: "Privat — Story (Geschichte)",
    useCase: "story",
    category: "privat",
    description: "Centered heading + caps subheading, a 5-up masonry gallery with hover captions, and a paragraphs + dark fact-box block.",
    propsSummary: [
      { name: "heading / subheading", type: "string", required: true },
      { name: "gallery", type: "GalleryItem[]", required: true },
      { name: "paragraphs / factLines", type: "string[]", required: true },
    ],
    usedOn: ["/moebel-nach-mass"],
    screenshot: `${REF}/moebel-nach-mass/07-geschichte.jpg`,
  },
  {
    id: "privat-planner-cta",
    displayName: "Privat — Planner CTA",
    useCase: "planner-cta",
    category: "shared",
    description: "Dark marketing CTA: heading + body + underline link on the left, image with a yellow line-motif on the right. Defaults to the planner copy; also used by the gewerbe page.",
    propsSummary: [
      { name: "heading / body", type: "string", required: false },
      { name: "ctaLabel / ctaHref", type: "string", required: false },
      { name: "image / imageAlt", type: "string", required: false },
    ],
    usedOn: ["/moebel-nach-mass", "/gewerbe"],
    screenshot: `${REF}/moebel-nach-mass/08-moebelplaner-cta.jpg`,
  },

  // ── Shared (generic service sections) ─────────────────────────────────────
  {
    id: "shared-service-hero",
    displayName: "Shared — Service Hero",
    useCase: "hero",
    category: "shared",
    description: "Generic service-page hero: title, breadcrumb, optional intro + optional CTA pill, over a photo.",
    propsSummary: [
      { name: "title", type: "string", required: true },
      { name: "breadcrumb", type: "BreadcrumbItem[]", required: true },
      { name: "bgImage", type: "string", required: true },
      { name: "intro", type: "string", required: false },
      { name: "cta", type: "{ label; href }", required: false },
    ],
    usedOn: ["/gewerbe", "/moebelplaner", "/kontakt"],
    screenshot: `${REF}/gewerbeeinrichtung/band-0.jpg`,
  },
  {
    id: "shared-faq",
    displayName: "Shared — FAQ",
    useCase: "faq",
    category: "shared",
    description: "Two-column FAQ: left intro + arrow link, right accordion (rotating arrow). Eyebrow/CTA default to the Fast wording.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "items", type: "{ question; answer }[]", required: true },
      { name: "eyebrow / ctaHref / ctaLabel", type: "string", required: false },
    ],
    usedOn: ["/moebel-nach-mass", "/gewerbe", "/moebelplaner"],
    screenshot: `${REF}/moebel-nach-mass/10a-faq.jpeg`,
    isClient: true,
  },
  {
    id: "shared-testimonials",
    displayName: "Shared — Testimonials (3-up)",
    useCase: "testimonials",
    category: "shared",
    description: "Eyebrow + heading and a 3-card grid of customer reviews with avatars and star ratings.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "eyebrow", type: "string", required: false },
    ],
    usedOn: ["/moebel-nach-mass", "/gewerbe", "/moebelplaner"],
    screenshot: `${REF}/moebel-nach-mass/09-testimonials.jpg`,
  },
  {
    id: "shared-partner-carousel",
    displayName: "Shared — Partner Carousel",
    useCase: "logo-carousel",
    category: "shared",
    description: "Infinite-scroll marquee of partner logos.",
    propsSummary: [],
    usedOn: ["/kontakt"],
    screenshot: `${REF}/kontakt/band-2.jpg`,
  },
  {
    id: "shared-image-cta",
    displayName: "Shared — Expanding Image CTA",
    useCase: "image-cta",
    category: "shared",
    description: "Full-width image block with a gradient overlay, an oversized heading and an underline CTA link.",
    propsSummary: [
      { name: "image", type: "string", required: true },
      { name: "heading", type: "string", required: true },
      { name: "linkText", type: "string", required: true },
      { name: "href", type: "string", required: true },
      { name: "className", type: "string", required: false },
    ],
    usedOn: ["/moebel-nach-mass", "/gewerbe", "/moebelplaner"],
    screenshot: `${REF}/moebel-nach-mass/02b-massmoebel.jpg`,
  },

  {
    id: "shared-referenzen-hero",
    displayName: "Shared — Referenzen Hero (Collage)",
    useCase: "hero",
    category: "shared",
    description:
      "Reference-hub hero in ServiceHero typography, but with a collage of project photos as the background (mobile 2×2, desktop strip, thin dark seam) instead of a single image. Layered scrim keeps the white title/breadcrumb legible. Falls back to a full-bleed image when one is passed.",
    propsSummary: [
      { name: "title", type: "string", required: true },
      { name: "breadcrumb", type: "BreadcrumbItem[]", required: true },
      { name: "images", type: "ReferenzHeroImage[]", required: true },
      { name: "intro", type: "string", required: false },
    ],
    usedOn: ["/referenzen"],
    screenshot: `${REF}/gewerbeeinrichtung/band-0.jpg`,
  },
  {
    id: "shared-referenzen-grid",
    displayName: "Shared — Referenzen Grid (Aggregator)",
    useCase: "reference-grid",
    category: "shared",
    description:
      "Reference hub aggregator: eyebrow + heading + editorial lead, a centred category filter bar, and a dense image mosaic. Each tile is a full-bleed photo that reveals a dark overlay (category + title + 'Projekt entdecken') on hover/focus and links to the matching cluster or detail page. Reusable as a project teaser block on cluster pages.",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "leadParagraphs", type: "string[]", required: true },
      { name: "categories", type: "ReferenzCategory[]", required: true },
      { name: "projects", type: "ReferenzProject[]", required: true },
      { name: "eyebrow", type: "string", required: false },
    ],
    usedOn: ["/referenzen"],
    screenshot: `${REF}/sec7-raeume.png`,
    isClient: true,
  },

  // ── Gewerbe (commercial page) ─────────────────────────────────────────────
  {
    id: "gewerbe-intro-stats",
    displayName: "Gewerbe — Intro + Stats",
    useCase: "intro-stats",
    category: "gewerbe",
    description: "Commercial-page intro/stats band with a scroll count-up.",
    propsSummary: [
      { name: "since / sinceSub / heading / intro*", type: "string", required: true },
      { name: "bandImage / bandAlt", type: "string", required: true },
      { name: "col1–3 copy + links", type: "string", required: true },
      { name: "counterTarget / counterDuration", type: "number", required: true },
      { name: "counterUnit / counterPlus", type: "string", required: true },
    ],
    usedOn: ["/gewerbe"],
    screenshot: `${REF}/gewerbeeinrichtung/band-1.jpg`,
  },
  {
    id: "gewerbe-laden-gastro",
    displayName: "Gewerbe — Laden & Gastro",
    useCase: "feature-text",
    category: "gewerbe",
    description: "Retail/gastronomy feature: text intro + image strip showcasing shop and gastro fit-outs.",
    propsSummary: [
      { name: "ladenHeading / ladenParagraphs[]", type: "string", required: true },
      { name: "ladenImage / ladenImageAlt", type: "string", required: true },
      { name: "mosaic: {src,alt}[]", type: "object", required: true },
      { name: "gastroHeading / gastro* copy (before/bold/after splits)", type: "string", required: true },
    ],
    usedOn: ["/gewerbe"],
    screenshot: `${REF}/gewerbeeinrichtung/band-3.jpg`,
  },
  {
    id: "gewerbe-leistungen",
    displayName: "Gewerbe — Leistungen",
    useCase: "categories-list",
    category: "gewerbe",
    description: "Grid of commercial service categories (Praxis, Büro, Ladenbau, Hotel & Gastro, …).",
    propsSummary: [
      { name: "heading", type: "string", required: true },
      { name: "image1 / image1Alt / image2 / image2Alt", type: "string", required: true },
      { name: "row1 / row2: {title,description}[]", type: "object", required: true },
    ],
    usedOn: ["/gewerbe"],
    screenshot: `${REF}/gewerbeeinrichtung/band-6.jpg`,
  },
  {
    id: "gewerbe-warum",
    displayName: "Gewerbe — Warum",
    useCase: "story",
    category: "gewerbe",
    description: "Trust section with masonry gallery and a credentials block.",
    propsSummary: [
      { name: "heading / eyebrow / bodyParagraph / factBox", type: "string", required: true },
      { name: "gallery: {src,alt,caption,width,height}[]", type: "object", required: true },
    ],
    usedOn: ["/gewerbe"],
    screenshot: `${REF}/gewerbeeinrichtung/band-7.jpg`,
  },

  // ── Möbelplaner page ──────────────────────────────────────────────────────
  {
    id: "mp-schritte",
    displayName: "Möbelplaner — Schritte",
    useCase: "steps",
    category: "moebelplaner",
    description: "Numbered step sequence explaining how the online planner works.",
    propsSummary: [],
    usedOn: ["/moebelplaner"],
    screenshot: `${REF}/moebelplaner/band-1.jpg`,
  },
  {
    id: "mp-intro",
    displayName: "Möbelplaner — Intro",
    useCase: "feature-text",
    category: "moebelplaner",
    description: "Intro feature block for the planner page.",
    propsSummary: [],
    usedOn: ["/moebelplaner"],
    screenshot: `${REF}/moebelplaner/band-2.jpg`,
  },
  {
    id: "mp-prozess",
    displayName: "Möbelplaner — Prozess",
    useCase: "process",
    category: "moebelplaner",
    description: "Process explanation from planning to finished custom furniture.",
    propsSummary: [],
    usedOn: ["/moebelplaner"],
    screenshot: `${REF}/moebelplaner/band-3.jpg`,
  },

  // ── Kontakt page ──────────────────────────────────────────────────────────
  {
    id: "kontakt-formular-hero",
    displayName: "Kontakt — Formular-Hero",
    useCase: "contact-form",
    category: "kontakt",
    description:
      "Viewport-high contact hero: heading + breadcrumb + quick contact on the left, the contact form card on the right — form reachable without scrolling.",
    propsSummary: [
      { name: "title", type: "string", required: true },
      { name: "breadcrumb", type: "BreadcrumbItem[]", required: true },
      { name: "bgImage", type: "string", required: true },
    ],
    usedOn: ["/kontakt"],
    screenshot: `${REF}/kontakt/band-0.jpg`,
  },
  {
    id: "kontakt-panel",
    displayName: "Kontakt — Panel",
    useCase: "contact-form",
    category: "kontakt",
    description: "Contact panel: form, opening hours and phone (stacked under a hero).",
    propsSummary: [],
    usedOn: [],
    screenshot: `${REF}/kontakt/band-0.jpg`,
  },
  {
    id: "kontakt-standort",
    displayName: "Kontakt — Standort",
    useCase: "location",
    category: "kontakt",
    description: "Location section with address / map.",
    propsSummary: [],
    usedOn: ["/kontakt"],
    screenshot: `${REF}/kontakt/band-3.jpg`,
  },

  // ── Über uns page ─────────────────────────────────────────────────────────
  {
    id: "ueber-hero",
    displayName: "Über uns — Hero",
    useCase: "hero",
    category: "ueber",
    description: "About-page hero: oversized title + breadcrumb on a photo with a dark radial vignette, intro paragraph on the right.",
    propsSummary: [
      { name: "bgImage", type: "string", required: true },
      { name: "imageAlt", type: "string", required: true },
      { name: "title", type: "string", required: true },
      { name: "intro", type: "string", required: true },
      { name: "breadcrumb", type: "BreadcrumbItem[]", required: true },
    ],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/full-desktop.jpeg`,
  },
  {
    id: "ueber-timeline",
    displayName: "Über uns — Timeline",
    useCase: "timeline",
    category: "ueber",
    description: "Interactive company timeline: accent heading + intro, a clickable year selector with a gold progress line, and a card showing the active year's title, body and image.",
    isClient: true,
    propsSummary: [
      { name: "headingBefore / headingAccent / headingAfter", type: "string", required: true },
      { name: "intro", type: "string", required: true },
      { name: "years", type: "TimelineYear[]", required: true },
    ],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/02-timeline.jpeg`,
  },
  {
    id: "ueber-wofuer",
    displayName: "Über uns — Wofür wir stehen",
    useCase: "feature-text",
    category: "ueber",
    description: "Heading + arrow CTA, then an image and two value/feature text columns.",
    propsSummary: [
      { name: "heading / ctaLabel / ctaHref", type: "string", required: true },
      { name: "image / imageAlt", type: "string", required: true },
      { name: "columns", type: "WofuerColumn[]", required: true },
    ],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/03-wofuer.jpeg`,
  },
  {
    id: "ueber-logos",
    displayName: "Über uns — Logo Strip",
    useCase: "logo-carousel",
    category: "ueber",
    description: "Static centered row of partner / client logos.",
    propsSummary: [{ name: "logos", type: "LogoItem[]", required: true }],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/03-wofuer.jpeg`,
  },
  {
    id: "ueber-values",
    displayName: "Über uns — Werte",
    useCase: "values",
    category: "ueber",
    description: "Three values (Innovation/Tradition/Leidenschaft) around a centered cut-out figure, plus a mission heading and an arrow CTA.",
    propsSummary: [
      { name: "figure / figureAlt", type: "string", required: true },
      { name: "missionHeading / ctaLabel / ctaHref", type: "string", required: true },
      { name: "values", type: "ValueBlock[]", required: true },
    ],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/05-values.jpeg`,
  },
  {
    id: "ueber-nav-cards",
    displayName: "Über uns — Nav Cards",
    useCase: "nav-cards",
    category: "ueber",
    description: "Full-bleed row of three image cards (Leistungen/FAQ/Kontakt), each with a heading, corner arrow and a 'Mehr erfahren' link.",
    propsSummary: [{ name: "cards", type: "NavCard[]", required: true }],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/06-threecards.jpeg`,
  },
  {
    id: "ueber-fallbeispiel",
    displayName: "Über uns — Fallbeispiel",
    useCase: "case-study",
    category: "ueber",
    description: "Case study: eyebrow + oversized heading, image on the left and a quote box on the right.",
    propsSummary: [
      { name: "eyebrow / heading", type: "string", required: true },
      { name: "image / imageAlt", type: "string", required: true },
      { name: "quote", type: "string", required: true },
    ],
    usedOn: ["/ueber-uns"],
    screenshot: `${REF}/ueber-uns/07-fallbeispiel.jpeg`,
  },
] satisfies readonly SectionMeta[];

export type SectionId = (typeof SECTION_META)[number]["id"];
